#- This docker file is not really to run the tools in docker. It's mostly for testing that the full install works
# in linux
FROM ubuntu:24.04
    MAINTAINER Carsten Wulff <carsten@wulff.no>

RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

RUN apt-get update && \
    apt-get -y install sudo make verilator pandoc  \
    openssh-server  && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash aicex
RUN echo "aicex:aicex" | chpasswd && adduser aicex sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN echo  "X11UseLocalhost no\n" >> /etc/ssh/sshd_config

RUN echo "set num_threads=8\nset ngbehavior=hsa\nset ng_nomodcheck\n" >> /home/aicex/.spiceinit

EXPOSE 22

ARG DEBIAN_FRONTEND=noninteractive

RUN test -d /opt || mkdir /opt
RUN test -d /opt/eda || mkdir /opt/eda

WORKDIR /opt/
RUN sudo chown -R aicex:aicex /opt
USER aicex

COPY tests tests
WORKDIR /opt/tests

ENV LD_LIBRARY_PATH=/opt/eda/lib
ENV PATH=/opt/eda/bin:~/.local/bin:$PATH

RUN sudo make requirements && sudo apt-get autoremove -y && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*
RUN sudo make tt && sudo make clean

RUN sudo make eda_compile &&  sudo make eda_install && sudo make clean && sudo rm -rf yosys
RUN sudo apt-get update && sudo apt install -y python3.12-venv && sudo apt-get autoremove -y && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*
RUN sudo mkdir /opt/eda/python3
RUN sudo chown -R aicex:aicex /opt/eda/python3/
RUN python3 -m venv /opt/eda/python3
ENV PATH=/opt/eda/bin:/opt/eda/python3/bin:$HOME/.local/bin:$PATH
RUN python3 -m pip install matplotlib numpy click svgwrite pyyaml pandas tabulate wheel setuptools tikzplotlib
RUN sudo /bin/bash install_open_pdk.sh && cd /opt/pdk && sudo rm -rf skywater-pdk && sudo rm -rf open_pdks \
    && sudo find ./ -name "*.lib" -exec rm {} \;
RUN sudo apt-get update && \
    sudo apt-get -y install pandoc verilator &&  \
    sudo apt-get autoremove -y && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*

WORKDIR /home/aicex
RUN mkdir /home/aicex/.ssh

# Fix docker for UID
ENTRYPOINT sudo service ssh restart && tail -f /dev/null
