#- This docker file is not really to run the tools in docker. It's mostly for testing that the full install works
# in linux
FROM ubuntu:24.04
    MAINTAINER Carsten Wulff <carsten@wulff.no>

RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

RUN apt-get update && \
    apt-get -y install sudo make  \
    openssh-server  && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash aicex
RUN echo "aicex:aicex" | chpasswd && adduser aicex sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN echo  "X11UseLocalhost no\n" >> /etc/ssh/sshd_config

RUN echo "set num_threads=8\nset ngbehavior=hsa\nset ng_nomodcheck\n" >> /home/aicex/.spiceinit

EXPOSE 22

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /opt/
RUN sudo chown aicex:aicex /opt
USER aicex


#- If you want to do a fresh install, comment out the line below
#ARG STEP11=false

COPY tests tests
WORKDIR /opt/tests

ENV LD_LIBRARY_PATH=/opt/eda/lib
ENV PATH=/opt/eda/bin:$HOME/.local/bin:$PATH

RUN make requirements
RUN make tt
RUN make eda_compile
RUN sudo make eda_install
RUN python3 -m pip install matplotlib numpy click svgwrite pyyaml pandas tabulate wheel setuptools tikzplotlib
RUN source install_open_pdk.sh
RUN sudo rm -rf skywater-pdk
RUN sudo rm -rf open_pdk

WORKDIR /home/aicex
RUN mkdir /home/aicex/.ssh

ENTRYPOINT sudo service ssh restart && tail -f /dev/null
