#- This docker file is not really to run the tools in docker. It's mostly for testing that the full install works
# in linux
FROM wulffern/aicex:base_24.04
    MAINTAINER Carsten Wulff <carsten@wulff.no>

WORKDIR /opt/
USER aicex

#- If you want to do a fresh install, comment out the line below
#ARG STEP11=false

ENV LD_LIBRARY_PATH=/opt/eda/lib
ENV PATH=/opt/eda/bin:~/.local/bin:$PATH

RUN sudo rm -rf tests
COPY tests tests
WORKDIR /opt/tests

RUN sudo make eda_compile &&  sudo make eda_install && sudo make clean && sudo rm -rf yosys
RUN sudo apt-get update && sudo apt install -y python3.12-venv && sudo apt-get autoremove -y && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*
RUN sudo mkdir /opt/eda/python3
RUN sudo chown -R aicex:aicex /opt/eda/python3/
RUN python3 -m venv /opt/eda/python3
ENV PATH=/opt/eda/bin:/opt/eda/python3/bin:$HOME/.local/bin:$PATH
RUN python3 -m pip install matplotlib numpy click svgwrite pyyaml pandas tabulate wheel setuptools tikzplotlib
RUN sudo /bin/bash install_open_pdk.sh && cd /opt/pdk && sudo rm -rf skywater-pdk && sudo rm -rf open_pdks \
    && sudo find ./ -name "*.lib" -exec rm {} \;
RUN sudo apt-get update && \
    sudo apt-get -y install pandoc  \
    sudo apt-get autoremove -y && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*
WORKDIR /home/aicex


ENTRYPOINT sudo service ssh restart && tail -f /dev/null
